[package]
name = "amicis_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amicis_core.workspace = true
clap = { workspace = true, features = ["derive"] }
